vich_uploader:
    db_driver: orm

    mappings:
        image_user_avatar:
            uri_prefix: /images/user/avatar
            upload_destination: '%kernel.project_dir%/public/images/user/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true

        image_user_banner:
            uri_prefix: /images/user/banner
            upload_destination: '%kernel.project_dir%/public/images/user/banner'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true

        image_product:
            uri_prefix: /images/product
            upload_destination: '%kernel.project_dir%/public/images/product'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true